/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/mainscreen.ts" />
/// <reference path="../scenes/prince.ts" />
/// <reference path="../scenes/warrior.ts" />
///<reference path="../scenes/princedoor.ts"/>
///<reference path="../scenes/princekey.ts"/>
///<reference path="../scenes/warriordoor.ts"/>
///<reference path="../scenes/warriorkey.ts"/> 
//# sourceMappingURL=_reference.js.map